### ISSUE TITLE
Serverinfo

### ISSUE THREAD

**Issue by royalus** [sandarutharuneth/ivongiveaways#23]
![Screenshot 2023-04-01 011900](https://user-images.githubusercontent.com/59321692/229248936-093aa37f-5deb-477b-b6c4-c45a37840a71.jpg)

help me pls i stuck at this error

**Comment by sandarutharuneth** [comment]
Check your bot on dev portal and allow the intents. This error occurs because you didn't allowed the required  intents to the bot.

**Comment by royalus** [comment]
![Screenshot 2023-04-02 011900](https://user-images.githubusercontent.com/59321692/229289629-e29168b3-d502-4d25-be0a-f0ffe5c8edf9.jpg)

already allowed it

**Comment by sandarutharuneth** [comment]
Check permissions aswell to the bot. This can happen when bot doesn't have required perms or if you're running the commands on unauthorized perms channel.

**Comment by SoundDr0ut** [comment]
you guys cant fix Serverinfo and servericon command cuz its still not working

**Comment by sandarutharuneth** [comment]
We implemented all fixes to the current version of IVON and this version seems to be doing fine with the intendent version of the discord.js version

**Comment by SoundDr0ut** [comment]
alright, thanks
